version: '3'

services:

### PHP-FPM ##############################################
  php-fpm:
    build: ./images/php-fpm
    volumes:
      - ./images/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./images/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./apps:/var/www/html
    links:
      - redis
    networks:
      - backend

### NGINX Server #########################################
  nginx:
    build: ./images/nginx
    volumes:
      - ./apps:/var/www/html
      - ./logs/nginx:/var/log/nginx
      - ./images/nginx/sites-available:/etc/nginx/sites-available
    ports:
      - "80:80"
      - "8001:8001"
      - "8002:8002"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

### Composer ################################################
  composer:
    build: ./images/composer
    volumes:
      - ./apps:/var/www/html

### Redis ################################################
  redis:
    build: ./images/redis
    volumes:
      - ./databases/redis:/data
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
